# Worksheet 9A: NumPy

NumPy is one of the most fundamental external package used by Python users. Its array structure is a core component of its functionality offering functionalities functionalities beyond what's possible with Python's built-in data structures in a concise & efficient way.

Let's start by installing the library using `pip` (here we're using a Jupyter magic command to execute the shell command within the notebook):

In [6]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 8.3 MB/s eta 0:00:0000:0100:01
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart the kernel to use updated packages.


If the installation was successful you should be able to import the package:

In [7]:
import numpy as np

---
## Q1: Creation

Arrays are one of the most important data structures in NumPy. Arrays can be initialised through a number of [creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html). Let's look at a few of them.

Consider the following `list`:

In [8]:
l = [1, 2, 3, 4, 5, 6]

We can create the equivalent NumPy array using the original data as follows:

In [9]:
a = np.array(l)
a

array([1, 2, 3, 4, 5, 6])

Notice that its type isn't a `list`:

In [10]:
type(a)

numpy.ndarray

### Q1 a

Similarly, to how we could create `l1` using `range` as follows:

In [11]:
list(range(1, 7))

[1, 2, 3, 4, 5, 6]

NumPy also provides an analogous method:

In [12]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

Note how we don't need to cast the result to `list`, since an array is immediately returned by `arange`. In fact, if we did this, we would cast the result to a Python `list`.

This package also provides the capability of initialising array with particular values. The following examples initialise arrays of `3` elements with a specific value:

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.full(3, 2)

array([2, 2, 2])

---
## Shape

Let's talk about an array's [`shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html), which is an attribute that can be accessed from an array instance:

In [16]:
a.shape

(6,)

This gives an output similar to what we would get when checking the `len` of a `list`:

In [17]:
len(l)

6

The `shape` isn't a single integer though, but a tuple with an integer. The reason for this is that NumPy supports multiple dimensions. Let's construct a $2 \times 3$ array:

In [18]:
m = np.array([[1, 2, 3], [4, 5, 6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

Now the `shape` gives us the dimensions in the form of `(row, column)`, but the length of the list gives us the number of nested lists:

In [19]:
m.shape

(2, 3)

The length of the list

In [20]:
print(m.tolist())
print(len(m.tolist()))

[[1, 2, 3], [4, 5, 6]]
2


### Q1: Reshaping

We could [`transpose`](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) a multi-dimensional array, which inverts the rows & columns:

In [21]:
m_T = m.transpose()
m_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
m_T.shape

(3, 2)

A more flexible method is [`reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html), which allows us to specify a custom shape:

In [23]:
m.reshape((6, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

There has to be enough elements in the error to fill the specified shape, otherwise, an error is raised:

In [24]:
m.reshape((11, 2))

ValueError: cannot reshape array of size 6 into shape (11,2)

Note how `m` is still the $2 \times 3$ array we original had. Since the `reshape` method doesn't reshape the array in-place, but returns a new array which is reshaped.

In [25]:
m

array([[1, 2, 3],
       [4, 5, 6]])

`reshape` arguments can be `-1` when we want NumPy to infer the resultant elements along a particular dimension:

In [26]:
m.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
a.reshape((-1, 1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

#### Q1 a

Write code to re-create `m` from the contents of `a` using `reshape`:

In [29]:
# answer:
m = a.reshape((2, 3))
m

array([[1, 2, 3],
       [4, 5, 6]])

#### Q1 b

Write code to re-create `a` from the contents of `m` using `reshape`:

In [30]:
# answer:
a = m.reshape((1, 6))
a

array([[1, 2, 3, 4, 5, 6]])

### Q2

We can create multi-dimensional arrays of a custom shape without needing to use `reshape`.

#### Q2 a

Create an array `a1` which is a $3 \times 3$ array using [`ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) (without using `reshape`).

In [32]:
# answer:
a1 = np.ones((3, 3))
a1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Q2 b

Use the [`zeros_like`](https://numpy.org/doc/stable/reference/generated/numpy.zeros_like.html) method to create an array `a2` which is the same shape of `a1` (without using `reshape`).

In [33]:
# answer:
a2 = np.zeros_like(a1)
a2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---
## Arithmetic & Conditional operations

One of the most powerful functionalities of NumPy array is the ease by which we can perform arithmetic & conditional operations.

In [34]:
x = np.arange(1, 4)
x

array([1, 2, 3])

In [35]:
x - 1

array([0, 1, 2])

Note, that the original contents of `x` aren't modified:

In [36]:
x

array([1, 2, 3])

For these changes to take effect we have to assign the result to the original variable:

In [37]:
x -= 1
x

array([0, 1, 2])

Conditional operators are also supported. For example:

In [38]:
x > 2

array([False, False, False])

In [39]:
x == 2

array([False, False,  True])

In [40]:
x % 2 == True

array([False,  True, False])

Apart from doing these operations against a single value, we can also perform element-wise operations between 2 arrays:

In [41]:
y = np.arange(4, 7)
y

array([4, 5, 6])

In [42]:
x + y

array([4, 6, 8])

In [43]:
x - y

array([-4, -4, -4])

In [44]:
x * y

array([ 0,  5, 12])

In addition to making the resulting code more concise, the code is also much more efficient thanks to NumPy's built-in vectorisation capabilities. Let's compare this to list comprehension (feel free to compare it against a `for` loop as well).

In [45]:
n = 10000
a = np.random.random(n)
b = np.random.random(n)
a.shape

(10000,)

In [48]:
%%timeit
[a_i * b_i for a_i, b_i in zip(a, b)]

1.21 ms ± 1.65 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [47]:
%%timeit
a * b

4.49 µs ± 99.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


These operations also work on multi-dimensional arrays:

In [46]:
z = np.array([[2, 11, 5],
              [10, 12, 13]])
z

array([[ 2, 11,  5],
       [10, 12, 13]])

In [49]:
z * 2

array([[ 4, 22, 10],
       [20, 24, 26]])

In [50]:
z > 10

array([[False,  True, False],
       [False,  True,  True]])

In [51]:
z + z

array([[ 4, 22, 10],
       [20, 24, 26]])

### Q3: Broadcasting 

Let's now try performing an operation between arrays of a different shape:

In [52]:
z - x

array([[ 2, 10,  3],
       [10, 11, 11]])

Why does this work? Explain what's happening & in what cases this won't work. Feel free to modify the operation between the arrays to understand what's happening.

*answer:*
In the above example, z and x are both 2D array. The operation z-x subtracts each element in the x array from the corresponding element in the z array, known as element-wise subtraction. This operation will only work if the z and x arrays have the same number of rows and columns. If the arrays have different shapes, it will result in an error.


### Q4: Methods

There are a number of methods on arrays which perform different computations.

#### Q4 a

The [`min`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.min.html) method computes the minimum number of an array:

In [53]:
z.min()

2

But what if we wanted to get the minimum for each column? Provide the code to do this. *Hint: you should be able to do this by specifying an additional parameter to `min`.*

In [57]:
# answer:
z.min(axis=0)

array([ 2, 11,  5])

#### Q4 b

Use the [`clip`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.clip.html) method to return an array whose elements are between `0` & `9`.

In [58]:
# answer:
z.clip(0, 9)

array([[2, 9, 5],
       [9, 9, 9]])

#### Matrix operations

We can perform multiplication between matrices

In [59]:
z * z

array([[  4, 121,  25],
       [100, 144, 169]])

But this is element-wise multiplication & not matrix multiplication:

In [60]:
np.matmul(z, z.transpose())

array([[150, 217],
       [217, 413]])

Remember that when performing matrix multiplication between matrices of sizes $n \times m$ & $m \times l$, the result is a matrix of size $n \times l$.

In [61]:
m

array([[1, 2, 3],
       [4, 5, 6]])

Let's no compute matrix multiplication between a square matrix & its inverse:

In [62]:
m = np.array([
    [2, 6, 7],
    [2, 6, 5],
    [1, 1, 2],
])

I = np.matmul(m, np.linalg.inv(m))
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Remember that multiplying a matrix by its inverse is equal to the identity matrix: $A A^-1 = I$.

In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

If we try this with different values, we might get some rounding errors:

In [64]:
m = np.array([
    [2, 4, 7],
    [3, 6, 9],
    [1, 1, 2],
])

I = np.matmul(m, np.linalg.inv(m))
I

array([[ 1.00000000e+00, -3.33066907e-16, -2.22044605e-16],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [ 2.22044605e-16, -2.22044605e-16,  1.00000000e+00]])

This is a [common issue in floating point implementations](https://stackoverflow.com/q/21895756), but we can round to get the desired output:

In [65]:
np.around(I)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [66]:
np.array_equal(np.around(I), np.identity(3))

True

## Concatenation

### [`append`](https://numpy.org/doc/stable/reference/generated/numpy.append.html)

Similar to `list.append`, we can append items to arrays.

In [67]:
np.append(a, 4)

array([0.8686067 , 0.82078787, 0.46400389, ..., 0.63171928, 0.80722884,
       4.        ])

Notice how the syntax is slightly different to `list`s:

In [68]:
l.append(4)
l

[1, 2, 3, 4, 5, 6, 4]

The main reason is that the `append` operation doesn't happen in-place, so the original array wasn't changed by our previous operation:

In [69]:
a

array([0.8686067 , 0.82078787, 0.46400389, ..., 0.17359949, 0.63171928,
       0.80722884])

In [70]:
a = np.append(a, 4)  # assign the result to change the array
a

array([0.8686067 , 0.82078787, 0.46400389, ..., 0.63171928, 0.80722884,
       4.        ])

Multiple elements can be added at once by supplying an iterable instead of a single element:

In [71]:
np.append(a, [5, 6])

array([0.8686067 , 0.82078787, 0.46400389, ..., 4.        , 5.        ,
       6.        ])

With `list.append` the list would have been added as a single element in the list, which is why we would use `extend` instead to get the same sequence as above:

In [72]:
l.extend([5, 6])
l

[1, 2, 3, 4, 5, 6, 4, 5, 6]

Since NumPy's `append` accepts either a single element or a sequence of elements, the following statements would produce the same sequence:

In [73]:
np.append(a, 5)

array([0.8686067 , 0.82078787, 0.46400389, ..., 0.80722884, 4.        ,
       5.        ])

In [74]:
np.append(a, [5])

array([0.8686067 , 0.82078787, 0.46400389, ..., 0.80722884, 4.        ,
       5.        ])

We can also append along a particular dimension for multi-dimensional arrays:

In [75]:
m = np.array([[1, 2, 3], [5, 6, 7]])
m

array([[1, 2, 3],
       [5, 6, 7]])

In [76]:
np.append(m, [[4], [8]], axis=1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Notice how we are appending a "column" array since we are appending along `axis` `1` of `m`.

### Stacking

While append is generally useful for appending individual elements, stacking is a more versatile functionality which allows us to stack arrays against each other along an axis, to create a larger array. Let's consider the following arrays:

In [77]:
m1 = np.arange(0, 4)
m1

array([0, 1, 2, 3])

In [78]:
m2 = np.arange(4, 8)
m2

array([4, 5, 6, 7])

We could stack horizontally:

In [79]:
m3 = np.hstack((m1, m2))
m3

array([0, 1, 2, 3, 4, 5, 6, 7])

The results is something similar to what would happen with `append`.

However, if we stack vertically, we would end up with a multi-dimensional array:

In [80]:
m3 = np.vstack((m1, m2))
m3

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Notice how, similar to `append`, both `hstack` & `vstack` don't modify the array in-place, but return a new array.

We can also stack multi-dimensional arrays against each other, as long as the dimension we're stacking against matches.

In [81]:
rows, columns = m3.shape

In [82]:
# the number of rows in m4 does not necessarily have to be equal to m3, but the number of columns has to!
m4 = np.arange(8, 32).reshape((-1, columns))
m4

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [83]:
m5 = np.vstack((m3, m4))
m5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [84]:
# the number of columns in m6 does not necessarily have to be equal to m3, but the number of rows has to!
m6 = np.arange(8, 32).reshape((rows, -1))
m6

array([[ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [85]:
m7 = np.hstack((m3, m6))
m7

array([[ 0,  1,  2,  3,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 4,  5,  6,  7, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

---
## Array access

Let's use the following array

In [86]:
a = np.arange(1, 17)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

We can access elements in an array similar to a list:

In [87]:
a[0]

1

In [88]:
a[-1]

16

In [89]:
a[:2]

array([1, 2])

In [90]:
a[1:17:2]

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [91]:
a[0:17:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

Let's now consider multi-dimensional arrays:

In [121]:
m = np.arange(1, 17).reshape((4, 4))
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Individual elements could be accessed like lists:

In [93]:
m[0][1]

2

However, we can specifiy multiple indices for each dimension in one go:

In [94]:
m[0, 1]

2

This syntax allows us to access multiple elements easier. For example, if we wanted to access the first column of an array, this becomes much more straight-forward.

In [95]:
[x[1] for x in m]

[2, 6, 10, 14]

In [96]:
m[:, 1]

array([ 2,  6, 10, 14])

Where the `:` indicates that we want the entire slice along that dimension. This is similar to how we can write `a[:2]` or `a[2:]` to indicate "from the start" or "till the end", respectively.

### Q5

#### Q5 a

Write the code to get the first 2 columns of `m`, by using the array access directly. _Hint: remember that the end index is not inclusive when accessing a slice._

In [120]:
# answer:
m[:, :2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]])

#### Q5 b

Write the code to get columns `0` & `2` (the odd numbers) from `m`, by using the array access directly. _Hint: the columns are spaced by 1 column._

In [98]:
# answer:
m[:, [0, 2]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15]])

#### Q5 c

Write the code to get the `2`, `4`, `10`, & `12` from `m`, by using the array access directly. *Hint: the elements are spaced by 1 column & 1 row.*

In [145]:
# answer:
m[[0, 0, 2, 2], [1, 3, 1, 3]]

array([ 2,  4, 10, 12])

### Q6

You can also access elements by specifying a mask:

In [113]:
x = np.arange(10)
x[[True, True, True, False, False, False, True, False, True, True]]

array([0, 1, 2, 6, 8, 9])

This gives back the elements whose corresponding index is `True`.

Write the code to retrieve the elements which are even from `y`. You should not use a loop to do this & your answer should be generic for any array. _Hint: Remember that we get an array of `bool`s by directly by performing conditional operations on an array._

In [114]:
y = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 6, 9],
])

In [118]:
# answer:
y[y%2==0]

array([2, 2, 4, 6, 6])

## Appendix

This notebook gave you a brief overview of the NumPy package. In this notebook we mostly looked at how we can exploit the vectorisation capabilites to do certain operations with less code & more efficiently.

You are encouraged to go over the documentation & search for tutorials to explore more functionalities that the package has to offer. An exercise you can do is to go over the notebooks where we worked with lists & try replacing each list with a NumPy array to see how you can achieve the same functionality.

In [ ]:
-